DROP TABLE IF EXISTS `tdTask` CASCADE ;
DROP TABLE IF EXISTS `tdList` CASCADE ;

CREATE TABLE IF NOT EXISTS `tdList` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(25) NOT NULL);
CREATE TABLE IF NOT EXISTS `tdTask` (`id` BIGINT PRIMARY KEY AUTO_INCREMENT, `todo` VARCHAR(40) NOT NULL);

